from abc import ABC, abstractmethod
from backend.app.core.schemas import SignalFrame

class BioSignalDevice(ABC):
    @abstractmethod
    async def connect(self) -> None: ...
    @abstractmethod
    async def disconnect(self) -> None: ...
    @abstractmethod
    async def start_stream(self) -> None: ...
    @abstractmethod
    async def stop_stream(self) -> None: ...
    @abstractmethod
    async def get_samples(self) -> SignalFrame: ...
