import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const API='http://localhost:8000';
function App(){
 const [session,setSession]=useState<any>();const [run,setRun]=useState<any>();const [starting,setStarting]=useState(false);
 async function start(){setStarting(true);try{const result=await (await fetch(API+'/api/v1/simulations/start',{method:'POST'})).json();setSession(result.session);setRun(result.simulation)}finally{setStarting(false)}}
 useEffect(()=>{if(!session?.id)return;const timer=window.setInterval(async()=>{const result=await (await fetch(`${API}/api/v1/simulations/${session.id}`)).json();setSession(result.session);setRun(result.simulation)},500);return()=>window.clearInterval(timer)},[session?.id]);
 const logs=run?.logs||[];
 return <main><header><span className="orb">N</span><div><h1>NIVO</h1><p>BioSignal-to-Intent development console</p></div><button onClick={start} disabled={starting||run?.state==='STREAMING'}>{starting?'Starting…':'Start simulator'}</button></header><section className="hero"><div><label>ASSISTANT STATUS</label><h2>{run?.state||'SLEEPING'}</h2><p>The dashboard starts one backend-owned stream from <code>example.npy</code>; it does not open a second ingestion socket.</p></div><div className="pulse"/></section><div className="grid"><Card t="Stream" v={run?.state||'Not started'}/><Card t="Session" v={session?.id||'No active session'}/><Card t="Packets" v={String(run?.packets||0)}/><Card t="Signal quality" v={session?`${Math.round((session.signal_quality||0)*100)}%`:'—'}/><Card t="Intent" v={session?.intents?.at(-1)?.intent||'Waiting for calibrated pattern'}/><Card t="Source" v="example.npy · 250 Hz · 6 channels"/></div><section className="logs"><label>STREAMING LOG</label><pre>{logs.length?logs.map((l:any)=>`[${l.timestamp}] ${l.message}`).join('\n'):'Waiting for the simulator to start.'}</pre></section></main>
}; function Card(p:{t:string,v:string}){return <article><label>{p.t}</label><strong>{p.v}</strong></article>}createRoot(document.getElementById('root')!).render(<App/>);
